sudo: required

env:
  global:
    - COMMIT=$TRAVIS_COMMIT
    - TAG_BRANCH=${TRAVIS_BRANCH/\//--}
  matrix:
   - REPO=simple-php-project.web
   - REPO=simple-php-project.nginx

language: bash

services:
  - docker

script:
  - docker build -f docker/web/Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG_BRANCH
  - docker tag $REPO:$COMMIT $REPO:latest
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $REPO
