sudo: required

env:
  global:
    - COMMIT=$TRAVIS_COMMIT
    - TAG_BRANCH=${TRAVIS_BRANCH/\//--}
  matrix:
   - REPO=pravindahal/simple-php-project.web
   - REPO=pravindahal/simple-php-project.nginx

language: bash

services:
  - docker

script:
  - docker pull $REPO
  - docker build -f docker/web/Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG_BRANCH
  - docker tag $REPO:$COMMIT $REPO:latest
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $REPO

notifications:
  slack: futurehome:uOTCFkT2d7kTcrymCTUFaEcv
