version: '2'
services:
  web:
    image: pravindahal/simple-php-project.web:${TAGNAME}
  nginx:
    image: pravindahal/simple-php-project.nginx:${TAGNAME}
    ports:
      - "8000:80"
    links:
      - web
