version: '2'
services:
  webshop:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "9000:9000"
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    links:
      - webshop
