version: '2'
services:
  webshop:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - httproot:/var/www/
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    links:
      - webshop
    volumes:
      - httproot:/var/www/
volumes:
  httproot: {}
