version: '2'
services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "9000:9000"
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    links:
      - web
